#include "main.h"
#include "liblvgl/llemu.h"
#include "pros/screen.hpp"
#include "pros/colors.hpp"
#include <cmath>
#include <algorithm>
#include <cstdio>
#include <vector>
#include "pros/link.hpp"
/**
 * A callback function for LLEMU's center button.
 *
 * When this callback is fired, it will toggle line 2 of the LCD text between
 * "I was pressed!" and nothing.
 */
/* This is an default function generated by PROS
void on_center_button() {
	static bool pressed = false;
	pressed = !pressed;
	if (pressed) {
		pros::lcd::set_text(2, "I was pressed!");
	} else {
		pros::lcd::clear_line(2);
	}
}
*/
/**
 * Runs initialization code. This occurs as soon as the program is started.
 *
 * All other competition modes are blocked by initialize; it is recommended
 * to keep execution time for this mode under a few seconds.
 */

struct PID{
	double Kp, Ki, Kd;
	double integral = 0;
	double lastError = 0;
	double lastTime = 0;
	bool started = false;

	PID(double kp, double ki, double kd) : Kp(kp), Ki(ki), Kd(kd) {}

    double update(double target, double current, double now) {
        double error = target - current;
        double dt = now - lastTime;
        if (dt <= 0) dt = 0.02;	// 20ms
        if (!started) { started = true; lastTime = now; lastError = error; return Kp * error; }

      integral += error * dt;
        double derivative = (error - lastError) / dt;

        lastError = error;
        lastTime = now;

        double out = Kp * error + Ki * integral + Kd * derivative;
        return out;  // clamp to motor range, -127~127
    }

	void reset() { integral = 0; lastError = 0; started = false; }
};

void initialize() {
	pros::lcd::initialize();
	pros::lcd::set_text(0, "The moon landing was a hoax");
	pros::lcd::set_text(1, "The moon landing was a hoax");

}

/**
 * Runs while the robot is in the disabled state of Field Management System or
 * the VEX Competition Switch, following either autonomous or opcontrol. When
 * the robot is enabled, this task will exit.
 */
void disabled() {}

/**
 * Runs after initialize(), and before autonomous when connected to the Field
 * Management System or the VEX Competition Switch. This is intended for
 * competition-specific initialization routines, such as an autonomous selector
 * on the LCD.
 *
 * This task will exit when the robot is enabled and autonomous or opcontrol
 * starts.
 */
void competition_initialize() {}

/**
 * Runs the user autonomous code. This function will be started in its own task
 * with the default priority and stack size whenever the robot is enabled via
 * the Field Management System or the VEX Competition Switch in the autonomous
 * mode. Alternatively, this function may be called in initialize or opcontrol
 * for non-competition testing purposes.
 *
 * If the robot is disabled or communications is lost, the autonomous task
 * will be stopped. Re-enabling the robot will restart the task, not re-start it
 * from where it left off.
 */
void autonomous() {
	// 直行 3 米：目标用编码器度数表示（需按你的轮子直径校准）
	const double DEGREES_PER_METER = 1600.0;  // 约 2.75" 测轮：1米≈1600度，按实车调
	const double TARGET_DEGREES = 3.0 * DEGREES_PER_METER;  // 3 米

	pros::MotorGroup left_motors({-3, 11, -12});
	pros::MotorGroup right_motors({15, -16, 17});
	pros::Rotation forwardOdom(4);
	PID drivePid(0.4, 0.02, 0.02);
	drivePid.reset();

	pros::lcd::clear();
	pros::lcd::set_text(0, "Auto: 3m straight");

	while (true) {
		double now = pros::millis() / 1000.0;
		double current = forwardOdom.get_position();
		double out = drivePid.update(TARGET_DEGREES, current, now);

		left_motors.move((int)out);
		right_motors.move((int)out);

		// LCD：目标、当前、误差、输出
		pros::lcd::print(1, "target: %.0f  cur: %.0f", TARGET_DEGREES, current);
		pros::lcd::print(2, "err: %.1f  out: %.0f", drivePid.lastError, out);

		if (fabs(drivePid.lastError) < 5.0) {
			left_motors.move(0);
			right_motors.move(0);
			pros::lcd::set_text(3, "Done");
			break;
		}

		pros::delay(20);
	}
}

/**
 * Runs the operator control code. This function will be started in its own task
 * with the default priority and stack size whenever the robot is enabled via
 * the Field Management System or the VEX Competition Switch in the operator
 * control mode.
 *
 * If no competition control is connected, this function will run immediately
 * following initialize().
 *
 * If the robot is disabled or communications is lost, the
 * operator control task will be stopped. Re-enabling the robot will restart the
 * task, not resume it from where it left off.
 */
void opcontrol() {
	pros::Controller master(pros::E_CONTROLLER_MASTER);
	// -------------------------------
	// DRIVE MOTOR GROUPS
	// -------------------------------
	pros::MotorGroup left_motors({-3, 11, -12});
	pros::MotorGroup right_motors({15,-16, 17});
	pros::MotorGroup drivetrain({3, -11, 12, 15, -16, 17});
	// -------------------------------
	// MECHANISM MOTORS
	// -------------------------------
	pros::Motor motorIntake(18);
	pros::Motor motorArm(20);
	pros::Motor wing(14);
	// -------------------------------
	// ODOMETRY SENSORS
	// -------------------------------
	pros::Rotation forwardOdom(4);   // tracking wheel
	pros::Imu imu(6);                // IMU

	while (true) {
		int Left_move_control = master.get_analog(ANALOG_LEFT_Y);    // Gets amount forward/backward from left joystick
		int right_move_control = master.get_analog(ANALOG_RIGHT_Y);  // Gets the turn left/right from right joystick
		left_motors.move(Left_move_control);                      // Sets left motor voltage
		right_motors.move(right_move_control);                     // Sets right motor voltage

		pros::lcd::print(2, "Left: %d Right: %d ",Left_move_control, right_move_control);// Prints the joystick values to the LCD for debugging purposes

		pros::delay(20);                               // Run for 20 ms then update
	}
}


